site_name: avm99963
theme:
  name: 'material'
  language: 'es'
  icon:
    logo: material/help-box
repo_name: avm99963/support.avm99963.com
repo_url: https://github.com/avm99963/support.avm99963.com
extra_css: ["css/styles.css"]
markdown_extensions:
  - admonition
  - footnotes
nav:
  - 'Sobre esta web': 'index.md'
  - 'Chrome':
    - 'Malware en Chrome': 'chrome/malware.md'
    - 'Inhabilitar extensiones de Chrome': 'chrome/diagnostico-extensiones.md'
    - 'Chrome no carga p치ginas web': 'chrome/no-carga-paginas-web.md'
    - 'Canales de Chrome': 'chrome/canales.md'
    - 'Error con certificado': 'chrome/error-certificado.md'
    - 'Traducciones':
      - 'Descarte y recarga de pesta침as': 'chrome/traducciones/descarte-recarga-pestanas.md'
    - 'Para desarrolladores':
      - 'Vida de un objeto URLRequest': 'chrome/desarrolladores/vida-de-una-url-request.md'
      - 'Un curso r치pido sobre diagn칩stico de problemas con chrome://net-internals': 'chrome/desarrolladores/curso-diagnostico-net-internals.md'
