name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 #2.3.5
        with:
          fetch-depth: 0

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@786c1c8c1c5ab4ceda14f1579cf417cbd6288825 #1.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
