name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #2.4.0
        with:
          fetch-depth: 0

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@b1bb7cbaa91997e57d601309aac18facb028ff7d #1.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
